// This file was autogenerated by calcdeps.py
goog.addDependency("../calculated_deps.js", [], []);
goog.addDependency("../tests.js", [], ['goog.testing.jsunit']);
goog.addDependency("testrunner.js", ['goog.testing.TestRunner'], ['goog.testing.TestCase']);
goog.addDependency("base.js", [], []);
goog.addDependency("testcase.js", ['goog.testing.TestCase', 'goog.testing.TestCase.Error', 'goog.testing.TestCase.Order', 'goog.testing.TestCase.Result', 'goog.testing.TestCase.Test'], ['goog.object', 'goog.testing.asserts', 'goog.testing.stacktrace']);
goog.addDependency("object.js", ['goog.object'], []);
goog.addDependency("jsunit.js", ['goog.testing.jsunit'], ['goog.testing.TestCase', 'goog.testing.TestRunner']);
goog.addDependency("asserts.js", ['goog.testing.JsUnitException', 'goog.testing.asserts'], ['goog.testing.stacktrace']);
goog.addDependency("stacktrace.js", ['goog.testing.stacktrace', 'goog.testing.stacktrace.Frame'], []);
